
CREATE USER gsk
WITH PASSWORD 'gskabdwal'
VALID UNTIL '2025-01-14';

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER
ON TABLE product TO gsk;

GRANT CREATE 
ON DATABASE "Supermart" 
TO gsk;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER 
ON ALL TABLES IN SCHEMA public TO gsk;

REVOKE ALL 
ON TABLE product
FROM gsk;

ALTER USER gsk
RENAME TO gskabdwal;

DROP USER gskabdwal;

REVOKE ALL PRIVILEGES ON DATABASE "Supermart"
FROM gskabdwal;

REVOKE ALL PRIVILEGES ON TABLE product
FROM gskabdwal;

REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public
FROM gskabdwal;

DROP USER gskabdwal;

SELECT * FROM pg_user; 

SELECT DISTINCT USER FROM pg_stats; 
